/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class AccessToken {
    
    constructor(accessToken) { 
        
        AccessToken.initialize(this, accessToken);
    }
    
    static initialize(obj, accessToken) { 
        obj['Access-Token'] = accessToken;
    }
    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccessToken();

            if (data.hasOwnProperty('Access-Token')) {
                obj['Access-Token'] = ApiClient.convertToType(data['Access-Token'], Object);
            }
        }
        return obj;
    }
    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AccessToken.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

}

AccessToken.RequiredProperties = ["Access-Token"];

AccessToken.prototype['Access-Token'] = undefined;

export default AccessToken;

