/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class GameID {
    
    constructor(gameId) { 
        
        GameID.initialize(this, gameId);
    }

    
    static initialize(obj, gameId) { 
        obj['game_id'] = gameId;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameID();

            if (data.hasOwnProperty('game_id')) {
                obj['game_id'] = ApiClient.convertToType(data['game_id'], Object);
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameID.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GameID.RequiredProperties = ["game_id"];


GameID.prototype['game_id'] = undefined;






export default GameID;

