/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class GameConfig {
    
    constructor(players, boardSize, blockSize) { 
        
        GameConfig.initialize(this, players, boardSize, blockSize);
    }

    
    static initialize(obj, players, boardSize, blockSize) { 
        obj['players'] = players;
        obj['board_size'] = boardSize;
        obj['block_size'] = blockSize;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameConfig();

            if (data.hasOwnProperty('players')) {
                obj['players'] = ApiClient.convertToType(data['players'], Object);
            }
            if (data.hasOwnProperty('board_size')) {
                obj['board_size'] = ApiClient.convertToType(data['board_size'], Object);
            }
            if (data.hasOwnProperty('block_size')) {
                obj['block_size'] = ApiClient.convertToType(data['block_size'], Object);
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameConfig.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

GameConfig.RequiredProperties = ["players", "board_size", "block_size"];


GameConfig.prototype['players'] = undefined;


GameConfig.prototype['board_size'] = undefined;


GameConfig.prototype['block_size'] = undefined;






export default GameConfig;

