/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';


class Piece {
    
    constructor(shape) { 
        
        Piece.initialize(this, shape);
    }

    
    static initialize(obj, shape) { 
        obj['shape'] = shape;
    }

    
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Piece();

            if (data.hasOwnProperty('shape')) {
                obj['shape'] = ApiClient.convertToType(data['shape'], Object);
            }
        }
        return obj;
    }

    
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Piece.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

Piece.RequiredProperties = ["shape"];


Piece.prototype['shape'] = undefined;






export default Piece;

